// Date: 14.06.2013 04:13:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package cobaltmod.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAltar extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
  
  public ModelAltar()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 113);
      Shape1.addBox(-6F, 0F, -7F, 12, 1, 14);
      Shape1.setRotationPoint(0F, 23F, 0F);
      Shape1.setTextureSize(64, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 101);
      Shape2.addBox(-5F, 0F, -5F, 10, 2, 10);
      Shape2.setRotationPoint(0F, 21F, 0F);
      Shape2.setTextureSize(64, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 94);
      Shape3.addBox(-3F, 0F, -3F, 6, 1, 6);
      Shape3.setRotationPoint(0F, 20F, 0F);
      Shape3.setTextureSize(64, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 85);
      Shape4.addBox(-1F, 0F, -1F, 2, 7, 2);
      Shape4.setRotationPoint(0F, 15F, 0F);
      Shape4.setTextureSize(64, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 71);
      Shape5.addBox(-5F, 0F, -6F, 10, 2, 12);
      Shape5.setRotationPoint(0F, 12F, 0F);
      Shape5.setTextureSize(64, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 64);
      Shape6.addBox(0F, 0F, 0F, 3, 4, 3);
      Shape6.setRotationPoint(3F, 11F, -7F);
      Shape6.setTextureSize(64, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 64);
      Shape7.addBox(0F, 0F, 0F, 3, 4, 3);
      Shape7.setRotationPoint(3F, 11F, 4F);
      Shape7.setTextureSize(64, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 64);
      Shape8.addBox(0F, 0F, 0F, 3, 4, 3);
      Shape8.setRotationPoint(-6F, 11F, -7F);
      Shape8.setTextureSize(64, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 64);
      Shape9.addBox(0F, 0F, 0F, 3, 4, 3);
      Shape9.setRotationPoint(-6F, 11F, 4F);
      Shape9.setTextureSize(64, 128);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 56);
      Shape10.addBox(-3F, 0F, -3F, 6, 2, 6);
      Shape10.setRotationPoint(0F, 14F, 0F);
      Shape10.setTextureSize(64, 128);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  public void renderModel (float f1)
	{
		Shape1.render(f1);
		Shape2.render(f1);
		Shape3.render(f1);
		Shape4.render(f1);
		Shape5.render(f1);
		Shape6.render(f1);
		Shape7.render(f1);
		Shape8.render(f1);
		Shape9.render(f1);
		Shape10.render(f1);
	}
}
