// Date: 26.12.2014 00:03:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package cobaltmod.entity;

import java.util.Random;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCobaltGuardian extends ModelBase {
	// fields
	ModelRenderer Bottom;
	ModelRenderer Bottom1;
	ModelRenderer Middle;
	ModelRenderer Top;
	ModelRenderer Middleout;
	ModelRenderer Middleout1;
	ModelRenderer Middleout2;
	ModelRenderer Middleout3;
	Random rand = new Random();

	public ModelCobaltGuardian() {
		textureWidth = 128;
		textureHeight = 128;

		Bottom = new ModelRenderer(this, 0, 0);
		Bottom.addBox(-8F, 0F, -8F, 16, 16, 16);
		Bottom.setRotationPoint(0F, 8F, 0F);
		Bottom.setTextureSize(128, 128);
		Bottom.mirror = true;
		setRotation(Bottom, 0F, 0F, 0F);
		Bottom1 = new ModelRenderer(this, 0, 32);
		Bottom1.addBox(-8F, 0F, -8F, 16, 16, 16);
		Bottom1.setRotationPoint(0F, -8F, 0F);
		Bottom1.setTextureSize(128, 128);
		Bottom1.mirror = true;
		setRotation(Bottom1, 0F, 0F, 0F);
		Middle = new ModelRenderer(this, 0, 0);
		Middle.addBox(-8F, 0F, -8F, 16, 16, 16);
		Middle.setRotationPoint(0F, -24F, 0F);
		Middle.setTextureSize(128, 128);
		Middle.mirror = true;
		setRotation(Middle, 0F, 0F, 0F);
		Top = new ModelRenderer(this, 0, 0);
		Top.addBox(-8F, 0F, -8F, 16, 16, 16);
		Top.setRotationPoint(0F, -40F, 0F);
		Top.setTextureSize(128, 128);
		Top.mirror = true;
		setRotation(Top, 0F, 0F, 0F);
		Middleout = new ModelRenderer(this, 0, 0);
		Middleout.addBox(0F, -8F, -8F, 16, 16, 16);
		Middleout.setRotationPoint(8F, -16F, 0F);
		Middleout.setTextureSize(128, 128);
		Middleout.mirror = true;
		setRotation(Middleout, 0F, 0F, 0F);
		Middleout1 = new ModelRenderer(this, 0, 0);
		Middleout1.addBox(-16F, -8F, -8F, 16, 16, 16);
		Middleout1.setRotationPoint(-8F, -16F, 0F);
		Middleout1.setTextureSize(128, 128);
		Middleout1.mirror = true;
		setRotation(Middleout1, 0F, 0F, 0F);
		Middleout2 = new ModelRenderer(this, 0, 0);
		Middleout2.addBox(-8F, -8F, 0F, 16, 16, 16);
		Middleout2.setRotationPoint(0F, -16F, 8F);
		Middleout2.setTextureSize(128, 128);
		Middleout2.mirror = true;
		setRotation(Middleout2, 0F, 0F, 0F);
		Middleout3 = new ModelRenderer(this, 0, 0);
		Middleout3.addBox(-8F, -8F, -16F, 16, 16, 16);
		Middleout3.setRotationPoint(0F, -16F, -8F);
		Middleout3.setTextureSize(128, 128);
		Middleout3.mirror = true;
		setRotation(Middleout3, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {

		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Bottom.render(f5);
		Bottom1.render(f5);
		Middle.render(f5);
		Top.render(f5);
		Middleout.render(f5);
		Middleout1.render(f5);
		Middleout2.render(f5);
		Middleout3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
